// Code generated by goctl. DO NOT EDIT.
package types

type OcrReq struct {
	Base64 string `json:"base64"`
}

type Position struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

type OcrReply struct {
	Content    string     `json:"content"`
	Confidence float64    `json:"probability"`
	Pos        []Position `json:"pos"`
}
