// Code generated by goctl. DO NOT EDIT.
package types

type OcrReq struct {
	Base64 string `json:"base64"`
	Url    string `json:"url"`
}

type Position struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

type SingleOcrReply struct {
	Content    string     `json:"content"`
	Confidence float64    `json:"probability"`
	Pos        []Position `json:"pos"`
}

type OcrReply struct {
	Code    int              `json:"code"`
	Msg     string           `json:"msg"`
	Replies []SingleOcrReply `json:"Replies"`
}
